name: kraken
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - python-bidi
  - lxml
  - regex
  - requests
  - click>=8.1
  - numpy
  - pillow>=9.2.0
  - scipy
  - jinja2
  - conda-forge::torchvision-cpu>=0.5.0
  - conda-forge::pytorch-cpu>=1.7.1,<1.14
  - jsonschema
  - scikit-image>=0.17.0,<=0.19.3
  - shapely>=2.0
  - pyvips
  - imagemagick>=7.1.0
  - coremltools>=3.3
  - pyarrow
  - conda-forge::pytorch-lightning>=1.7.0
  - conda-forge::torchmetrics
  - pip
  - albumentations
  - rich
  - pip:
    - file:.
