package:
  name: kraken
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

requirements:
  build:
     - python
     - setuptools
     - pbr
  run:
     - python-bidi
     - lxml
     - regex
     - requests
     - click>=8.1
     - numpy
     - pillow>=6.2.2
     - scipy
     - protobuf
     - jinja2
     - conda-forge::torchvision
     - conda-forge::pytorch>=1.7.1,<=1.11.99
     - cudatoolkit
     - jsonschema
     - scikit-image
     - shapely>=1.7
     - pyvips
     - coremltools
     - pyarrow
     - conda-forge::pytorch-lightning>=1.6.0
     - conda-forge::albumentations
     - conda-forge::rich
about:
  home: http://kraken.re
  license: Apache License
  summary: 'OCR/HTR engine for all the languages'
